export const SCENE_KEYS = Object.freeze({
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  WORLD_SCENE: 'WORLD_SCENE',
  BATTLE_SCENE: 'BATTLE_SCENE',
  TITLE_SCENE: 'TITLE_SCENE',
  OPTIONS_SCENE: 'OPTIONS_SCENE',
  TEST_SCENE: 'TEST_SCENE',
  MONSTER_PARTY_SCENE: 'MONSTER_PARTY_SCENE',
  MONSTER_DETAILS_SCENE: 'MONSTER_DETAILS_SCENE',
  INVENTORY_SCENE: 'INVENTORY_SCENE',
  CUTSCENE_SCENE: 'CUTSCENE_SCENE',
  DIALOG_SCENE: 'DIALOG_SCENE',
});
